name = "mcp-email-aws-ses-smtp"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[vars]
MCP_PROTOCOL_VERSION = "2025-06-18"
EMAIL_PROVIDER = "aws-ses-smtp"

[env.production]
# Set via GitHub Actions or Cloudflare dashboard
# AWS_SES_USERNAME = "your-smtp-username"
# AWS_SES_PASSWORD = "your-smtp-password"
# AWS_REGION = "us-east-1"
# EMAIL_DEFAULT_FROM = "noreply@yourdomain.com"

[env.development]
# Same as production
